export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const FETCH_MACHINE_TYPES_PENDING = 'FETCH_MACHINE_TYPES_PENDING'
export const FETCH_MACHINE_TYPES_SUCCESS = 'FETCH_MACHINE_TYPES_SUCCESS'
export const FETCH_MACHINE_TYPES_FAIL = 'FETCH_MACHINE_TYPES_FAIL'

export const FETCH_MACHINE_TYPE_PENDING = 'FETCH_MACHINE_TYPE_PENDING'
export const FETCH_MACHINE_TYPE_SUCCESS = 'FETCH_MACHINE_TYPE_SUCCESS'
export const FETCH_MACHINE_TYPE_FAIL = 'FETCH_MACHINE_TYPE_FAIL'

export const CREATE_MACHINE_TYPE_PENDING = 'CREATE_MACHINE_TYPE_PENDING'
export const CREATE_MACHINE_TYPE_SUCCESS = 'CREATE_MACHINE_TYPE_SUCCESS'
export const CREATE_MACHINE_TYPE_FAIL = 'CREATE_MACHINE_TYPE_FAIL'

export const UPDATE_MACHINE_TYPE_PENDING = 'UPDATE_MACHINE_TYPE_PENDING'
export const UPDATE_MACHINE_TYPE_SUCCESS = 'UPDATE_MACHINE_TYPE_SUCCESS'
export const UPDATE_MACHINE_TYPE_FAIL = 'UPDATE_MACHINE_TYPE_FAIL'

export const DELETE_MACHINE_TYPE_PENDING = 'DELETE_MACHINE_TYPE_PENDING'
export const DELETE_MACHINE_TYPE_SUCCESS = 'DELETE_MACHINE_TYPE_SUCCESS'
export const DELETE_MACHINE_TYPE_FAIL = 'DELETE_MACHINE_TYPE_FAIL'

export const FETCH_MACHINES_PENDING = 'FETCH_MACHINES_PENDING'
export const FETCH_MACHINES_SUCCESS = 'FETCH_MACHINES_SUCCESS'
export const FETCH_MACHINES_FAIL = 'FETCH_MACHINES_FAIL'

export const FETCH_MACHINE_PENDING = 'FETCH_MACHINE_PENDING'
export const FETCH_MACHINE_SUCCESS = 'FETCH_MACHINE_SUCCESS'
export const FETCH_MACHINE_FAIL = 'FETCH_MACHINE_FAIL'

export const CREATE_MACHINE_PENDING = 'CREATE_MACHINE_PENDING'
export const CREATE_MACHINE_SUCCESS = 'CREATE_MACHINE_SUCCESS'
export const CREATE_MACHINE_FAIL = 'CREATE_MACHINE_FAIL'

export const UPDATE_MACHINE_PENDING = 'UPDATE_MACHINE_PENDING'
export const UPDATE_MACHINE_SUCCESS = 'UPDATE_MACHINE_SUCCESS'
export const UPDATE_MACHINE_FAIL = 'UPDATE_MACHINE_FAIL'

export const DELETE_MACHINE_PENDING = 'DELETE_MACHINE_PENDING'
export const DELETE_MACHINE_SUCCESS = 'DELETE_MACHINE_SUCCESS'
export const DELETE_MACHINE_FAIL = 'DELETE_MACHINE_FAIL'

export const FETCH_REGIONS_PENDING = 'FETCH_REGIONS_PENDING'
export const FETCH_REGIONS_SUCCESS = 'FETCH_REGIONS_SUCCESS'
export const FETCH_REGIONS_FAIL = 'FETCH_REGIONS_FAIL'

export const FETCH_REGION_PENDING = 'FETCH_REGION_PENDING'
export const FETCH_REGION_SUCCESS = 'FETCH_REGION_SUCCESS'
export const FETCH_REGION_FAIL = 'FETCH_REGION_FAIL'

export const CREATE_REGION_PENDING = 'CREATE_REGION_PENDING'
export const CREATE_REGION_SUCCESS = 'CREATE_REGION_SUCCESS'
export const CREATE_REGION_FAIL = 'CREATE_REGION_FAIL'

export const UPDATE_REGION_PENDING = 'UPDATE_REGION_PENDING'
export const UPDATE_REGION_SUCCESS = 'UPDATE_REGION_SUCCESS'
export const UPDATE_REGION_FAIL = 'UPDATE_REGION_FAIL'

export const DELETE_REGION_PENDING = 'DELETE_REGION_PENDING'
export const DELETE_REGION_SUCCESS = 'DELETE_REGION_SUCCESS'
export const DELETE_REGION_FAIL = 'DELETE_REGION_FAIL'